version: '2'
services:
    opala-app:
        image: opala
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://opala-mysql:3306/opala?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=opala-elasticsearch:9300
        ports:
            - 8080:8080
    opala-mysql:
        extends:
            file: mysql.yml
            service: opala-mysql
    opala-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: opala-elasticsearch
